"""Adicionando nova coluna à tabela

Revision ID: de03e457dd1a
Revises: 1aaf8fc36bdf
Create Date: 2024-12-31 10:56:53.709510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de03e457dd1a'
down_revision: Union[str, None] = '1aaf8fc36bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
